"""add_group_id

Revision ID: 266d171c8cf4
Revises: 001
Create Date: 2026-03-23 16:52:04.397489
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '266d171c8cf4'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('group_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_reservations_group_id'), 'reservations', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_group_id'), table_name='reservations')
    op.drop_column('reservations', 'group_id')
    # ### end Alembic commands ###
