"""add_maintenance_stock

Revision ID: 2a59f54f7f36
Revises: 003
Create Date: 2026-03-27 12:49:05.389252
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2a59f54f7f36'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_models', sa.Column('maintenance_stock', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_models', 'maintenance_stock')
    # ### end Alembic commands ###
